#!/usr/bin/env python3
"""Build a terminal-style GitHub profile README from profile.toml.

    build.py init --username U [--name N]     write profile.toml, README, workflow
    build.py fetch [--no-token]                refresh data/ from GitHub
    build.py render [--only a,b] [--static]    write assets/*.svg
    build.py readme                            rewrite the marker blocks in README.md
    build.py all [--no-fetch]                  fetch, render, readme, check
    build.py check [--strict]                  validate config and every SVG
    build.py eject [--out DIR] [--update]      vendor this engine into the repo
    build.py list                              show the enabled panels
    build.py themes                            show the palettes

Run it from the profile repository root (the folder with profile.toml) or
pass --root. Exit codes: 0 ok, 1 usage or runtime error, 2 check failure,
3 config error. A network failure never fails the build; the fetchers keep
their previous cache and say so.
"""

import argparse
import html
import json
import os
import re
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import profile_config  # noqa: E402
from theme import PALETTES, contrast  # noqa: E402

SKILL_ROOT = HERE.parent
TEMPLATES = SKILL_ROOT / "assets"
VERSION = (HERE / "VERSION").read_text().strip() if (HERE / "VERSION").exists() else "dev"

BEGIN = "<!-- profile:begin {name} -->"
END = "<!-- profile:end {name} -->"
INSERT = "<!-- profile:insert -->"
NOTICE = "<!-- generated by github-profile-designer; edits inside this block are overwritten -->"
KNOWN_BLOCKS = {
    "boot", "typing", "neofetch", "whoami", "snake", "lab", "plate", "systemctl", "stack",
    "gitlog", "activity", "languages", "finger", "install", "exit",
}


def fill_template(text, profile):
    """Replace the {{placeholders}} a template may carry."""
    values = {
        "name": profile.get("name", ""),
        "username": profile.get("username", ""),
        "user": profile.get("user", ""),
        "host": profile.get("host", "github"),
    }
    for key, value in values.items():
        text = text.replace("{{" + key + "}}", str(value))
    return text

# Default shell command shown in the heading above each panel.
HEADINGS = {
    "boot": "",
    "typing": "",
    "neofetch": "neofetch",
    "whoami": "whoami",
    "snake": "git-cal --snake",
    "lab": "plate-reader --last 96d; systemctl status",
    "plate": "plate-reader --last 96d",
    "systemctl": "systemctl status",
    "stack": "ls -F --color=auto ~/stack",
    "gitlog": "git log --oneline --decorate --date=short",
    "activity": "git log --oneline --all --since=90.days",
    "languages": "du -sh languages/* | sort -rh",
    "finger": "finger {user}",
    "exit": "exit",
}

# What each asset is made from, for the man page.
SOURCES = {
    "boot": ("render_boot.py", "profile.toml [boot] + build time", "daily"),
    "typing": ("render_typing.py", "profile.toml [typing]", "on change"),
    "neofetch": ("render_neofetch.py", "[neofetch] rows + data/github.json + data/contributions.json", "daily"),
    "portrait": ("render_portrait.py", "profile.toml [portrait]", "on change"),
    "info": ("render_info.py", "profile.toml [info]", "on change"),
    "snake": ("render_snake.py", "data/contributions.json (public calendar, no token)", "daily"),
    "plate": ("render_plate.py", "data/contributions.json, last 96 days", "daily"),
    "systemctl": ("render_systemctl.py", "profile.toml [[projects]]", "daily (uptime)"),
    "stack": ("render_stack.py", "profile.toml [stack]", "on change"),
    "gitlog": ("render_gitlog.py", "profile.toml [[timeline]]", "on change"),
    "activity": ("render_activity.py", "data/github.json (public events)", "daily"),
    "languages": ("render_languages.py", "data/github.json (bytes per language)", "daily"),
    "finger": ("render_finger.py", "profile.toml [finger] + build time", "daily"),
    "exit": ("render_exit.py", "profile.toml [exit] + build time", "daily"),
}


def _load_json(path, default):
    path = Path(path)
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except ValueError:
        return default


def _git_sha(root):
    try:
        return subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"], cwd=root, capture_output=True, text=True, timeout=5
        ).stdout.strip()
    except Exception:
        return ""


class Build:
    def __init__(self, root, config, static=False):
        self.root = Path(root).resolve()
        self.config = config
        self.static = static
        self.profile = config["profile"]
        self.width = config["theme"]["width"]
        self.dark, self.light = profile_config.themes(config)
        self.assets = self.root / config["paths"]["assets"]
        self.data = self.root / config["paths"]["data"]
        self.readme = self.root / config["paths"]["readme"]
        self.status = _load_json(self.data / "build.json", {})
        self._contrib = None
        self._github = None
        self._grid = None
        now = datetime.now(timezone.utc)
        self.build_info = {
            "generated_at": now.strftime("%Y-%m-%d %H:%M UTC"),
            "sha": _git_sha(self.root),
            "version": VERSION,
        }

    # --- data --------------------------------------------------------------
    @property
    def contributions(self):
        if self._contrib is None:
            self._contrib = _load_json(self.data / "contributions.json", {})
            if not self._contrib:
                import fetch_contributions
                self._contrib = fetch_contributions.empty_calendar(self.profile["username"])
        return self._contrib

    @property
    def github(self):
        if self._github is None:
            self._github = _load_json(self.data / "github.json", {})
        return self._github

    def portrait_grid(self):
        if self._grid is None and profile_config.enabled(self.config, "portrait"):
            import render_portrait
            self._grid = render_portrait.build_grid(self.config["portrait"], self.root)
        return self._grid or []

    def ctx(self):
        return {
            "profile": self.profile,
            "github": self.github,
            "contributions": self.contributions,
            "build": self.build_info,
            "timeline": self.config.get("timeline") or [],
            "portrait_config": self.config.get("portrait") or {},
            "portrait_grid": self.portrait_grid(),
        }

    def on(self, panel):
        return profile_config.enabled(self.config, panel)

    def on_with(self, panel, array_key):
        """Panels driven by an array table: on when the array exists, unless
        the panel's own section says enabled = false."""
        if panel in self.config:
            return self.on(panel)
        return bool(self.config.get(array_key))

    def section(self, panel):
        return self.config.get(panel) or {}

    # --- rendering ---------------------------------------------------------
    def renderers(self):
        """Ordered (panel, callable(theme) -> svg) for every enabled panel."""
        ctx = self.ctx()
        w = self.width
        out = []
        if self.on("boot"):
            import render_boot
            out.append(("boot", lambda t, cfg=self.section("boot"): render_boot.render(t, cfg, ctx, w, self.static)))
        if self.on("typing"):
            import render_typing
            out.append(("typing", lambda t, cfg=self.section("typing"): render_typing.render(t, cfg, w)))
        if self.on("neofetch"):
            import render_neofetch
            out.append(("neofetch", lambda t, cfg=self.section("neofetch"): render_neofetch.render(t, cfg, ctx, w, self.static)))
        else:
            if self.on("portrait"):
                import render_portrait
                out.append(("portrait", lambda t, cfg=self.section("portrait"): render_portrait.render(t, cfg, self.portrait_grid(), self.static)))
            if self.on("info"):
                import render_info
                cfg = self.section("info")
                out.append(("info", lambda t, cfg=cfg: render_info.render(t, cfg, self.profile, int(cfg.get("width", 490)), self.static)))
        if self.on("snake"):
            import render_snake
            cfg = dict(self.section("snake"))
            src = (self.status.get("sources") or {}).get("contributions") or {}
            if src.get("status") == "cached" and src.get("fetched_at"):
                cfg["cached_note"] = src["fetched_at"][:10]
            out.append(("snake", lambda t, cfg=cfg: render_snake.render(t, cfg, self.contributions, w)[0]))
        if self.on("plate"):
            import render_plate
            cfg = self.section("plate")
            out.append(("plate", lambda t, cfg=cfg: render_plate.render(t, cfg, ctx, int(cfg.get("width", 370)), self.static)))
        if self.on_with("systemctl", "projects"):
            import render_systemctl
            cfg = dict(self.section("systemctl"))
            cfg["projects"] = self.config.get("projects") or []
            width = int(cfg.get("width", w - int(self.section("plate").get("width", 370)) if self.on("plate") else w))
            out.append(("systemctl", lambda t, cfg=cfg, width=width: render_systemctl.render(t, cfg, ctx, width, self.static)))
        if self.on("stack"):
            import render_stack
            out.append(("stack", lambda t, cfg=self.section("stack"): render_stack.render(t, cfg, ctx, w, self.static)))
        if self.on_with("gitlog", "timeline"):
            import render_gitlog
            out.append(("gitlog", lambda t, cfg=self.section("gitlog"): render_gitlog.render(t, cfg, ctx, w, self.static)))
        if self.on("activity"):
            import render_activity
            out.append(("activity", lambda t, cfg=self.section("activity"): render_activity.render(t, cfg, self.github, w, self.static)))
        if self.on("languages"):
            import render_languages
            out.append(("languages", lambda t, cfg=self.section("languages"): render_languages.render(t, cfg, self.github, w, self.static)))
        if self.on("finger"):
            import render_finger
            out.append(("finger", lambda t, cfg=self.section("finger"): render_finger.render(t, cfg, ctx, w, self.static)))
        if self.on("exit"):
            import render_exit
            out.append(("exit", lambda t, cfg=self.section("exit"): render_exit.render(t, cfg, ctx, w, self.static)))
        return out

    def asset_path(self, name, variant="dark"):
        suffix = "" if not self.light else f"-{variant}"
        return self.assets / f"{name}{suffix}.svg"

    def render_all(self, only=None):
        written = []
        for name, renderer in self.renderers():
            if only and name not in only:
                continue
            for variant, theme in (("dark", self.dark), ("light", self.light)):
                if theme is None:
                    continue
                svg = renderer(theme)
                ET.fromstring(svg)  # well-formed, or we stop here
                path = self.asset_path(name, variant)
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(svg, encoding="utf-8")
                written.append(path)
        return written

    # --- README ------------------------------------------------------------
    def expand(self, text):
        """Fill {user} and {host} without choking on other braces in user text."""
        return str(text).replace("{user}", self.profile["user"]).replace("{host}", self.profile["host"])

    def prompt(self):
        return self.expand(self.profile.get("prompt") or "{user}@{host}:~$")

    def heading(self, panel, section=None):
        section = section if section is not None else self.section(panel)
        command = section.get("heading", HEADINGS.get(panel, panel))
        if not command:
            return ""
        return f"### `{self.prompt()} {self.expand(command)}`\n\n"

    def image_html(self, name, alt, width=None, align=""):
        width = width or self.width
        alt = html.escape(alt, quote=True)
        rel = self.config["paths"]["assets"]
        attrs = f' align="{align}"' if align else ""
        if self.light:
            dark, light = f"./{rel}/{name}-dark.svg", f"./{rel}/{name}-light.svg"
            return (
                "<picture>\n"
                f'  <source media="(prefers-color-scheme: dark)" srcset="{dark}">\n'
                f'  <source media="(prefers-color-scheme: light)" srcset="{light}">\n'
                f'  <img src="{dark}" width="{width}" alt="{alt}"{attrs}>\n'
                "</picture>"
            )
        return f'<img src="./{rel}/{name}.svg" width="{width}" alt="{alt}"{attrs}>'

    def side_by_side(self, images):
        """Two panels on one row: adjacent inline images, no table.

        A table adds GitHub's cell padding and borders, so it comes out wider
        than the single panels and scrolls on phones; adjacent images sum to
        the page width exactly and wrap when the screen is narrow. align="top"
        (an attribute GitHub keeps) lines up the cards' top edges.
        """
        return "<p>\n" + "".join(images) + "\n</p>"

    def alt(self, panel, default):
        return self.section(panel).get("alt") or default

    def blocks(self):
        """name -> markdown for every README block, in page order."""
        b = {}
        name = self.profile.get("name", self.profile["username"])
        host = self.profile["host"]
        if self.on("boot"):
            b["boot"] = self.image_html("boot", self.alt("boot", f"Boot log and login on host {host}: {name}, refreshed daily by GitHub Actions"))
        if self.on("typing"):
            b["typing"] = self.image_html("typing", self.alt("typing", " / ".join(self.section("typing").get("lines", []))))
        if self.on("neofetch"):
            b["neofetch"] = self.heading("neofetch") + self.image_html(
                "neofetch", self.alt("neofetch", f"neofetch: ASCII portrait beside role, focus, stack and contact fields for {name}"))
        elif self.on("portrait") or self.on("info"):
            cells = []
            if self.on("portrait"):
                cells.append(self.image_html("portrait", self.alt("portrait", "ASCII art portrait"), self.section("portrait").get("width", 370), align="top"))
            if self.on("info"):
                cells.append(self.image_html("info", self.alt("info", "Info card listing role, stack, location and contact"), self.section("info").get("width", 490), align="top"))
            b["whoami"] = self.heading("whoami", self.section("info") or self.section("portrait")) + self.side_by_side(cells)
        if self.on("snake"):
            total = self.contributions.get("total", 0)
            b["snake"] = self.heading("snake") + self.image_html(
                "snake", self.alt("snake", f"Contribution calendar for the last year with a snake eating the active days; {total} contributions"))
        have_plate = self.on("plate")
        have_units = self.on_with("systemctl", "projects")
        if have_plate and have_units:
            b["lab"] = self.heading("lab", self.section("systemctl")) + self.side_by_side([
                self.image_html("plate", self.alt("plate", "96-well plate: the last 96 days of contributions, one well per day"), self.section("plate").get("width", 370), align="top"),
                self.image_html("systemctl", self.alt("systemctl", "systemctl status of the flagship project"), self.section("systemctl").get("width", 490), align="top"),
            ]) + self.project_links()
        elif have_plate:
            b["plate"] = self.heading("plate") + self.image_html("plate", self.alt("plate", "96-well plate: the last 96 days of contributions, one well per day"), self.section("plate").get("width", 370))
        elif have_units:
            b["systemctl"] = self.heading("systemctl") + self.image_html("systemctl", self.alt("systemctl", "systemctl status of the flagship project")) + self.project_links()
        if self.on("stack"):
            groups = self.section("stack").get("groups") or []
            listing = "; ".join(", ".join(g.get("items", [])) for g in groups if isinstance(g, dict))
            b["stack"] = self.heading("stack") + self.image_html("stack", self.alt("stack", f"ls of ~/stack: {listing}"))
        if self.on_with("gitlog", "timeline"):
            subjects = "; ".join(e.get("subject", "") for e in self.config.get("timeline") or [] if isinstance(e, dict))
            b["gitlog"] = self.heading("gitlog") + self.image_html("gitlog", self.alt("gitlog", f"git log of milestones: {subjects}"))
        if self.on("activity"):
            b["activity"] = self.heading("activity") + self.image_html("activity", self.alt("activity", "Recent public GitHub activity, refreshed daily"))
        if self.on("languages"):
            b["languages"] = self.heading("languages") + self.image_html("languages", self.alt("languages", "Languages by bytes across repositories"))
        if self.on("finger"):
            b["finger"] = self.heading("finger") + self.image_html("finger", self.alt("finger", f"finger {self.profile['user']}: name, office, email and links")) + self.contact_links()
        if self.section("install").get("show"):
            b["install"] = self.install_block()
        if self.on("exit"):
            b["exit"] = self.heading("exit") + self.image_html("exit", self.alt("exit", f"logout; connection to {host} closed")) + "\n\n" + self.man_page()
        return b

    def project_links(self):
        links = []
        for project in self.config.get("projects") or []:
            if not isinstance(project, dict):
                continue
            url = project.get("url") or project.get("docs")
            if url:
                links.append(f"[{project.get('label') or project.get('name')}]({url})")
            for extra in project.get("links") or []:
                if isinstance(extra, dict) and extra.get("url"):
                    links.append(f"[{extra.get('label', extra['url'])}]({extra['url']})")
        return f"\n\n`xdg-open` {' · '.join(links)}" if links else ""

    def contact_links(self):
        section = self.section("finger")
        links = []
        for entry in section.get("links") or []:
            if isinstance(entry, dict) and entry.get("url"):
                links.append(f"[{entry.get('label', entry['url'])}]({entry['url']})")
        if not links:
            if section.get("mail"):
                links.append(f"[Email](mailto:{section['mail']})")
            if section.get("site"):
                links.append(f"[Website]({section['site']})")
        return f"\n\n`xdg-open` {' · '.join(links)}" if links else ""

    def install_block(self):
        repo = self.section("install").get("repo") or "yuvalkolodkingal/yuvalkolodkingal"
        one_liner = f"curl -fsSL https://raw.githubusercontent.com/{repo}/main/install.sh | sh"
        return (
            f"### `{self.prompt()} {one_liner}`\n\n"
            "Want a profile like this? That command installs two Agent Skills into every AI coding agent on your\n"
            "machine (Claude Code, Codex, Cursor, Copilot, Gemini CLI, OpenCode and more). Then ask your agent:\n"
            '"design my GitHub profile with github-profile-designer".\n\n'
            "```sh\n"
            f"{one_liner}\n"
            f"# or: npx skills add {repo}\n"
            f"# read first: curl -fsSLO https://raw.githubusercontent.com/{repo}/main/install.sh && less install.sh && sh install.sh\n"
            "```"
        )

    def engine_path(self):
        """Where the engine lives from the repository's point of view.

        Inside the repository: its relative path. Otherwise the vendored copy
        that `build.py eject` writes, which is what the daily job runs.
        """
        try:
            return HERE.relative_to(self.root).as_posix()
        except ValueError:
            return "scripts/profile-engine"

    def man_page(self):
        rows = []
        for name, _ in self.renderers():
            gen, source, cadence = SOURCES.get(name, ("", "", ""))
            rows.append(f"| `{self.asset_path(name).name}` | `{gen}` | {source} | {cadence} |")
        engine = self.engine_path()
        user = self.profile["username"]
        return (
            f"<details>\n<summary><code>man {user}</code></summary>\n\n"
            "**NAME**\n\n"
            f"{user} - a GitHub profile rendered as one terminal session\n\n"
            "**SYNOPSIS**\n\n"
            "```sh\n"
            f"pip install -r {engine}/requirements.txt\n"
            f"python {engine}/build.py all\n"
            "```\n\n"
            "**DESCRIPTION**\n\n"
            "Every panel on this page is an SVG generated by Python from `profile.toml` and committed to this\n"
            "repository. Nothing is fetched from a stats service at view time, so there is no rate limit to hit and\n"
            "no broken image when someone else's server goes down. Motion is CSS keyframes and SMIL inside each file,\n"
            "which GitHub plays inside an image, and every animated panel has a still form for readers who prefer\n"
            "reduced motion. A GitHub Actions job refreshes the data-driven panels daily.\n\n"
            "**FILES**\n\n"
            "| File | Made by | From | Refreshed |\n| :-- | :-- | :-- | :-- |\n" + "\n".join(rows) + "\n\n"
            "**SEE ALSO**\n\n"
            f"`{engine}/`, `install.sh`, `profile.toml`, `.github/workflows/`\n\n"
            "</details>"
        )

    def update_readme(self, create=True):
        blocks = self.blocks()
        if self.readme.exists():
            text = self.readme.read_text(encoding="utf-8")
        elif create:
            text = fill_template((TEMPLATES / "README.template.md").read_text(encoding="utf-8"), self.profile)
        else:
            raise SystemExit(f"{self.readme} does not exist")

        replaced, inserted = [], []
        missing = []
        for name, body in blocks.items():
            begin, end = BEGIN.format(name=name), END.format(name=name)
            start = text.find(begin)
            stop = text.find(end, start + len(begin)) if start != -1 else -1
            if start == -1:
                # An orphan end marker would pair with a later begin; drop it.
                if stop == -1 and end in text:
                    text = text.replace(end, "", 1)
                missing.append(name)
                continue
            if stop == -1:
                # An orphan begin marker: rebuild the block right there rather
                # than pairing it with some later block's end marker.
                text = text[:start] + begin + "\n" + NOTICE + "\n" + body + "\n" + end + text[start + len(begin):]
                replaced.append(name)
                continue
            text = text[: start + len(begin)] + "\n" + NOTICE + "\n" + body + "\n" + text[stop:]
            replaced.append(name)
        if missing:
            chunk = "\n\n".join(
                f"{BEGIN.format(name=n)}\n{NOTICE}\n{blocks[n]}\n{END.format(name=n)}" for n in missing
            )
            if INSERT in text:
                text = text.replace(INSERT, chunk, 1)
            else:
                text = text.rstrip("\n") + "\n\n" + chunk + "\n"
            inserted = missing
        # Drop stale blocks for panels that are no longer enabled. Blocks with
        # names the engine never generates belong to the person and stay.
        removed = []
        for name in re.findall(r"<!-- profile:begin ([a-z-]+) -->", text):
            if name in KNOWN_BLOCKS and name not in blocks:
                pattern = re.compile(
                    re.escape(BEGIN.format(name=name)) + r".*?" + re.escape(END.format(name=name)) + r"\n?", re.S
                )
                text, n = pattern.subn("", text)
                if n:
                    removed.append(name)
        self.readme.write_text(text, encoding="utf-8")
        return replaced, inserted, removed

    # --- status ------------------------------------------------------------
    def write_status(self, sources=None, panels=None):
        status = dict(self.status)
        status.update({
            "built_at": self.build_info["generated_at"],
            "sha": self.build_info["sha"],
            "version": VERSION,
        })
        if sources:
            status.setdefault("sources", {}).update(sources)
        if panels is not None:
            status["panels"] = panels
        self.data.mkdir(parents=True, exist_ok=True)
        (self.data / "build.json").write_text(json.dumps(status, indent=1) + "\n", encoding="utf-8")
        self.status = status
        return status


# --- commands ---------------------------------------------------------------

def cmd_init(args):
    root = Path(args.root)
    target = root / "profile.toml"
    if target.exists() and not args.force:
        print(f"{target} already exists (use --force to overwrite)")
        return 1
    username = args.username or os.environ.get("GH_USERNAME") or ""
    if not username:
        print("init needs --username")
        return 1
    name = args.name or username
    user = re.sub(r"[^a-z0-9]", "", username.split("-")[0].lower())[:12] or "me"
    template = (TEMPLATES / "profile.example.toml").read_text(encoding="utf-8")
    text = (template.replace("{{username}}", username).replace("{{name}}", name)
            .replace("{{user}}", user).replace("{{palette}}", args.palette or "tokyo-night"))
    target.write_text(text, encoding="utf-8")
    print(f"wrote {target}")
    readme = root / "README.md"
    if not readme.exists():
        text = (TEMPLATES / "README.template.md").read_text(encoding="utf-8")
        readme.write_text(fill_template(text, {"name": name, "username": username, "user": user, "host": "github"}), encoding="utf-8")
        print(f"wrote {readme}")
    elif INSERT not in readme.read_text(encoding="utf-8"):
        print(f"note: {readme} exists; add {INSERT} where the generated blocks should go, or they are appended")
    workflow = root / ".github" / "workflows" / "profile.yml"
    if not workflow.exists() and not args.no_workflow:
        workflow.parent.mkdir(parents=True, exist_ok=True)
        engine = os.path.relpath(HERE, root).replace(os.sep, "/")
        text = (TEMPLATES / "workflow.template.yml").read_text(encoding="utf-8")
        workflow.write_text(text.replace("{{engine}}", engine), encoding="utf-8")
        print(f"wrote {workflow} (engine path {engine})")
    (root / "data").mkdir(exist_ok=True)
    (root / "assets").mkdir(exist_ok=True)
    if not args.no_eject and HERE != (root / "scripts" / "profile-engine").resolve() and not HERE.is_relative_to(root):
        # The daily job runs on GitHub's runners, where this skill is not
        # installed, so the engine has to live in the repository.
        args.out, args.update = None, False
        cmd_eject(args)
    print("next: edit profile.toml, then run: build.py all")
    return 0


def cmd_fetch(build, args):
    user = build.profile["username"]
    build.data.mkdir(parents=True, exist_ok=True)
    token = None if args.no_token else (os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN"))
    sources = {}
    stamp = build.build_info["generated_at"]
    if build.on("snake") or build.on("plate") or build.on("neofetch"):
        import fetch_contributions
        build._contrib = fetch_contributions.fetch(user, build.data / "contributions.json")
        status = dict(fetch_contributions.LAST_STATUS)
        previous = (build.status.get("sources") or {}).get("contributions") or {}
        sources["contributions"] = {
            "status": status["status"],
            "fetched_at": stamp if status["status"] == "fresh" else previous.get("fetched_at", ""),
            "error": status.get("error", ""),
        }
    needs_github = any(build.on(p) for p in ("neofetch", "activity", "languages"))
    if needs_github:
        import fetch_github
        options = dict(build.config.get("data") or {})
        options.setdefault("exclude_repos", [f"{user}/{user}"])
        build._github = fetch_github.fetch(user, build.data / "github.json", token, options)
        status = dict(fetch_github.LAST_STATUS)
        previous = (build.status.get("sources") or {}).get("github") or {}
        sources["github"] = {
            "status": status["status"],
            "fetched_at": stamp if status["status"] in ("fresh", "partial") else previous.get("fetched_at", ""),
            "rate_remaining": status.get("rate_remaining", ""),
        }
    build.write_status(sources=sources)
    summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary:
        with open(summary, "a", encoding="utf-8") as handle:
            handle.write("| Source | Status | Fetched |\n| :-- | :-- | :-- |\n")
            for name, info in sources.items():
                handle.write(f"| {name} | {info['status']} | {info.get('fetched_at', '')} |\n")
    for name, info in sources.items():
        if info["status"] != "fresh":
            print(f"::warning::{name} is {info['status']}")
    return 0


def cmd_render(build, args):
    only = set(filter(None, (args.only or "").split(","))) or None
    total = 0
    written = build.render_all(only)
    for path in written:
        size = path.stat().st_size
        total += size
        print(f"  {path.relative_to(build.root)}  {size / 1024:.0f} KB")
    print(f"assets: {len(written)} files, {total / 1024:.0f} KB")
    build.write_status(panels=[name for name, _ in build.renderers()])
    return 0


def cmd_readme(build, args):
    replaced, inserted, removed = build.update_readme()
    rel = build.readme.relative_to(build.root)
    print(f"{rel}: updated {', '.join(replaced) or 'nothing'}")
    if inserted:
        print(f"{rel}: inserted new blocks {', '.join(inserted)}")
    if removed:
        print(f"{rel}: removed stale blocks {', '.join(removed)}")
    return 0


ALLOWED_NON_ASCII = set("…·●└─│├┌┐┘┬┴┼▁▂▃▄▅▆▇█░▒▓→←↑↓")


def cmd_check(build, args):
    errors = warnings = 0

    def error(message):
        nonlocal errors
        errors += 1
        print(f"error: {message}")

    def warn(message):
        nonlocal warnings
        warnings += 1
        print(f"warning: {message}")

    for theme in (build.dark, build.light):
        if theme is None:
            continue
        ratio = contrast(theme.fg, theme.bg)
        if ratio < 4.5:
            warn(f"{theme.name}: text contrast {ratio:.1f}:1 is under 4.5:1")

    svgs = sorted(build.assets.glob("*.svg"))
    if not svgs:
        warn(f"no SVGs in {build.assets}; run render first")
    for path in svgs:
        try:
            ET.parse(path)
        except ET.ParseError as exc:
            error(f"{path.name}: not well-formed XML ({exc})")
            continue
        text = path.read_text(encoding="utf-8")
        size = path.stat().st_size
        if "<script" in text:
            error(f"{path.name}: contains <script>; GitHub never runs it")
        if "<foreignObject" in text:
            error(f"{path.name}: contains <foreignObject>; renders blank inside <img>")
        body = re.sub(r'xmlns(:\w+)?="[^"]*"', "", text)
        body = re.sub(r'aria-label="[^"]*"', "", body)
        body = re.sub(r"<title>.*?</title>", "", body, flags=re.S)
        if re.search(r"@import|url\(\s*['\"]?https?:|href=\"https?:|href='https?:", body):
            error(f"{path.name}: references an external resource; it will not load inside <img>")
        animated = "<animate" in text or "@keyframes" in text
        if animated and "prefers-reduced-motion" not in text:
            error(f"{path.name}: animated but has no prefers-reduced-motion rule")
        odd = {c for c in re.sub(r"<[^>]+>", "", body) if ord(c) > 0x7E and c not in ALLOWED_NON_ASCII}
        if odd:
            warn(f"{path.name}: non-ASCII glyphs {''.join(sorted(odd))!r} may render as tofu in some fonts")
        if size > 300 * 1024:
            warn(f"{path.name}: {size // 1024} KB; keep SVGs under about 300 KB")
        elif not args.quiet:
            print(f"ok: {path.name} ({size // 1024} KB)")

    if build.readme.exists():
        text = build.readme.read_text(encoding="utf-8")
        for name in build.blocks():
            if BEGIN.format(name=name) not in text:
                warn(f"README has no block for {name}; run readme to insert it")
        for match in re.finditer(r'src="\./([^"]+)"', text):
            if not (build.root / match.group(1)).exists():
                error(f"README references missing file {match.group(1)}")
        if re.search(r"img\.shields\.io|github-readme-stats|streak-stats|readme-typing-svg|capsule-render", text):
            warn("README still loads images from a third-party service")
    else:
        warn("no README.md yet; run readme")

    print(f"check: {errors} error(s), {warnings} warning(s)")
    if errors or (args.strict and warnings):
        return 2
    return 0


def rewrite_engine_path(text, engine):
    """Point a workflow at a new engine folder.

    Workflows written from the template carry `# engine-path: <old>`; every
    occurrence of that path is replaced. Without the comment, path tokens
    ending in build.py or requirements.txt are re-rooted instead.
    """
    match = re.search(r"(?m)^# engine-path: (\S+)\s*$", text)
    if match:
        old = match.group(1)
        if old == engine:
            return text
        text = text.replace(old + "/", engine + "/").replace(old, engine)
        return text.replace(f"# engine-path: {old}", f"# engine-path: {engine}", 1) if f"# engine-path: {old}" in text else text
    return re.sub(
        r"(?<![\w/.-])(?:[\w./-]+/)?(build\.py|requirements\.txt)\b",
        lambda m: f"{engine}/{m.group(1)}",
        text,
    )


def cmd_eject(args):
    root = Path(args.root).resolve()
    out = (root / (args.out or "scripts/profile-engine")).resolve()
    if out.exists() and not args.update:
        print(f"{out} exists (use --update to refresh it)")
        return 1
    if out == HERE:
        print("the engine already lives in this repository; nothing to eject")
        return 0
    if out.exists():
        shutil.rmtree(out)
    shutil.copytree(HERE, out, ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
    (out / "VERSION").write_text(VERSION + "\n", encoding="utf-8")
    assets = out.parent / "profile-templates" if False else None  # templates stay with the skill
    print(f"copied the engine to {out.relative_to(root)} (version {VERSION})")
    workflow = root / ".github" / "workflows" / "profile.yml"
    engine = out.relative_to(root).as_posix()
    if workflow.exists():
        text = workflow.read_text(encoding="utf-8")
        new = rewrite_engine_path(text, engine)
        if new != text:
            workflow.write_text(new, encoding="utf-8")
            print(f"updated engine paths in {workflow.relative_to(root)}")
    else:
        template = (TEMPLATES / "workflow.template.yml").read_text(encoding="utf-8")
        workflow.parent.mkdir(parents=True, exist_ok=True)
        workflow.write_text(template.replace("{{engine}}", engine), encoding="utf-8")
        print(f"wrote {workflow.relative_to(root)} (engine path {engine})")
    print(f"daily builds now run python {engine}/build.py all without the skill installed")
    return 0


def cmd_list(build, args):
    print(f"profile: {build.profile['username']}  theme: {build.dark.name}" + (f" + {build.light.name}" if build.light else "") + f"  width: {build.width}")
    for name, _ in build.renderers():
        gen, source, cadence = SOURCES.get(name, ("", "", ""))
        print(f"  {name:10s} {build.asset_path(name).name:22s} {source}")
    return 0


def cmd_themes(args):
    for name, theme in PALETTES.items():
        kind = "dark " if theme.dark else "light"
        print(f"  {name:18s} {kind}  bg {theme.bg}  fg {theme.fg}  accent {theme.accent}")
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", default=".", help="profile repository root (default: current directory)")
    parser.add_argument("--profile", default="profile.toml", help="config file, relative to --root")
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("init", help="scaffold profile.toml, README.md and the workflow")
    p.add_argument("--username", help="GitHub login")
    p.add_argument("--name", help="display name")
    p.add_argument("--palette", help="theme name (see themes)")
    p.add_argument("--force", action="store_true")
    p.add_argument("--no-workflow", action="store_true")
    p.add_argument("--no-eject", action="store_true", help="do not vendor the engine into the repository")

    p = sub.add_parser("fetch", help="refresh data/ from GitHub")
    p.add_argument("--no-token", action="store_true")

    p = sub.add_parser("render", help="write the SVG panels")
    p.add_argument("--only", help="comma-separated panel names")
    p.add_argument("--static", action="store_true", help="no animation (for previews)")

    sub.add_parser("readme", help="rewrite the marker blocks in README.md")

    p = sub.add_parser("all", help="fetch, render, readme, check")
    p.add_argument("--no-token", action="store_true")
    p.add_argument("--no-fetch", "--offline", action="store_true", dest="no_fetch")
    p.add_argument("--static", action="store_true")

    p = sub.add_parser("check", help="validate the config, the SVGs and the README")
    p.add_argument("--strict", action="store_true", help="warnings fail too")
    p.add_argument("--quiet", action="store_true")

    p = sub.add_parser("eject", help="vendor the engine into this repository")
    p.add_argument("--out", help="destination folder (default scripts/profile-engine)")
    p.add_argument("--update", action="store_true")

    sub.add_parser("list", help="show the enabled panels")
    sub.add_parser("themes", help="show the palettes")

    args = parser.parse_args(argv)
    if args.command == "themes":
        return cmd_themes(args)
    if args.command == "init":
        return cmd_init(args)
    if args.command == "eject":
        return cmd_eject(args)

    try:
        config = profile_config.load(Path(args.root) / args.profile)
    except profile_config.ConfigError as exc:
        print(f"error: {exc}")
        return 3
    build = Build(args.root, config, static=getattr(args, "static", False))

    if args.command == "fetch":
        return cmd_fetch(build, args)
    if args.command == "render":
        return cmd_render(build, args)
    if args.command == "readme":
        return cmd_readme(build, args)
    if args.command == "check":
        return cmd_check(build, args)
    if args.command == "list":
        return cmd_list(build, args)
    if args.command == "all":
        if not args.no_fetch:
            cmd_fetch(build, args)
        args.only = None
        cmd_render(build, args)
        cmd_readme(build, args)
        args.strict = False
        args.quiet = True
        return cmd_check(build, args)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
