#!/usr/bin/env python3
"""Render the contribution snake as a looping animated SVG.

A snake crawls the calendar in a serpentine, column by column, and every
square it passes over gets eaten and drops back to empty. When the run ends
the whole thing resets and starts again.

This reads the same data/contributions.json the heatmap does, so the snake
eats real squares and stays in step with the graph above it. Nothing is
generated by a third-party action and there is no extra output branch.

Usage:
    python scripts/render_snake_svg.py
"""

import json
from pathlib import Path

from render_heatmap_svg import CELL, GAP, GRID_X, PITCH, to_columns
from theme import DIM, HEAT, MONO, card

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "contributions.json"
OUT = ROOT / "assets" / "snake.svg"

WIDTH = 860
GRID_Y = 26
STEP = 0.045            # seconds the head spends on each square
LEAD = 6                # squares of run-up and run-out beyond the grid

# Head first, then the body fading back to the tail. Purple rather than blue,
# so the snake reads against the squares it is eating instead of blending in.
SNAKE = ["#e6ccff", "#bf91f3", "#a370e0", "#8455c4", "#6a43a0"]


def serpentine(columns):
    """Every grid square in snake order: down one column, up the next."""
    path = []
    for week in range(len(columns)):
        rows = range(7) if week % 2 == 0 else range(6, -1, -1)
        for row in rows:
            path.append((week, row))
    return path


def render(payload):
    columns = to_columns(payload.get("days", []))
    grid_h = 7 * PITCH - GAP
    height = GRID_Y + grid_h + 26

    # Run-up on the left and run-out on the right, so the snake enters and
    # leaves cleanly instead of popping into existence mid-grid.
    body = serpentine(columns)
    path = [(-LEAD + offset, 0) for offset in range(LEAD)] + body
    path += [(len(columns) + offset, path[-1][1]) for offset in range(LEAD)]
    total = len(path) * STEP

    def place(cell):
        week, row = cell
        return GRID_X + week * PITCH, GRID_Y + row * PITCH

    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{WIDTH}" '
        f'height="{height}" viewBox="0 0 {WIDTH} {height}" role="img" '
        f'aria-label="A snake eating the contribution graph">',
        card(WIDTH, height),
    ]

    # Squares. Only the ones with contributions need an eating animation, so
    # a quiet year stays a small file.
    eaten_at = {cell: index for index, cell in enumerate(path)}
    for week, column in enumerate(columns):
        for row, day in enumerate(column):
            x, y = place((week, row))
            level = 0 if day is None else min(int(day.get("level", 0)), len(HEAT) - 1)
            rect = (
                f'<rect x="{x}" y="{y}" width="{CELL}" height="{CELL}" rx="2.5" '
                f'fill="{HEAT[level]}"'
            )
            if level == 0:
                out.append(rect + "/>")
                continue
            when = eaten_at[(week, row)] * STEP / total
            out.append(
                rect + ">"
                f'<animate attributeName="fill" calcMode="discrete" '
                f'values="{HEAT[level]};{HEAT[0]}" '
                f'keyTimes="0;{when:.5f}" dur="{total:.2f}s" '
                f'repeatCount="indefinite"/>'
                f"</rect>"
            )

    # The snake itself: each segment replays the head's path a step behind.
    for offset, color in enumerate(SNAKE):
        xs, ys = [], []
        for index in range(len(path)):
            x, y = place(path[max(index - offset, 0)])
            xs.append(str(x))
            ys.append(str(y))
        keys = ";".join(f"{i / len(path):.5f}" for i in range(len(path)))
        size = CELL if offset == 0 else CELL - 1
        nudge = 0 if offset == 0 else 0.5
        out.append(
            f'<rect width="{size}" height="{size}" rx="{3 if offset == 0 else 2.5}" '
            f'fill="{color}" x="-100" y="{GRID_Y}" '
            f'transform="translate({nudge},{nudge})">'
            f'<animate attributeName="x" calcMode="discrete" '
            f'values="{";".join(xs)}" keyTimes="{keys}" dur="{total:.2f}s" '
            f'repeatCount="indefinite"/>'
            f'<animate attributeName="y" calcMode="discrete" '
            f'values="{";".join(ys)}" keyTimes="{keys}" dur="{total:.2f}s" '
            f'repeatCount="indefinite"/>'
            f"</rect>"
        )

    out.append(
        f'<text x="{GRID_X}" y="{height - 8}" font-family="{MONO}" '
        f'font-size="10" fill="{DIM}">'
        f"{payload.get('stats', {}).get('active_days', 0)} squares on the menu"
        f"</text>"
    )
    out.append("</svg>")
    return "\n".join(out) + "\n", total


def main():
    payload = json.loads(DATA.read_text(encoding="utf-8"))
    svg, total = render(payload)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(svg, encoding="utf-8")
    print(f"{OUT}: {total:.1f}s loop")


if __name__ == "__main__":
    main()
